import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { TEMPLATE_KEYS, TEMPLATE_LANGUAGES, TEMPLATES } from './templates.ts';

export const TEMPLATES_DOC_PATH = fileURLToPath(
  new URL('../../../docs/TEMPLATES-TO-SUBMIT.md', import.meta.url),
);

const LANGUAGE_NAMES = { en: 'English (`en`)', hi: 'Hindi (`hi`)' } as const;

/** docs/TEMPLATES-TO-SUBMIT.md, generated from the registry so the two never drift. */
export function renderTemplatesDoc(): string {
  const out: string[] = [
    '# WhatsApp templates to submit',
    '',
    '<!-- Generated by `pnpm templates:doc` from packages/config/src/templates.ts. Do not edit by hand. -->',
    '',
    "Submit each template below in WhatsApp Manager (or your BSP) for the client's WhatsApp Business Account, in both languages.",
    'Use the exact **name**, **category** and **language**; body variables are positional (`{{1}}`, `{{2}}`, …) and quick-reply buttons must be in the order shown.',
    '',
    '- **Utility** templates relate to something the lead asked for (their enquiry or appointment).',
    '- **Marketing** templates are follow-ups and review requests; Meta charges more for them and users can mute them.',
    '- Meta may re-categorise a template on review. If it does, update the category in the dashboard so cost tracking stays right.',
    '- Hinglish leads receive the English template; the AI replies in Hinglish once the lead writes back.',
    '',
    '| Name | Category | Used for |',
    '|---|---|---|',
    ...TEMPLATE_KEYS.map(
      (k) => `| \`${TEMPLATES[k].providerName}\` | ${TEMPLATES[k].category} | ${TEMPLATES[k].purpose} |`,
    ),
    '',
  ];

  for (const key of TEMPLATE_KEYS) {
    const t = TEMPLATES[key];
    out.push(`## \`${t.providerName}\``, '', `- **Category:** ${t.category}`, `- **Purpose:** ${t.purpose}`);
    out.push(
      `- **Variables:** ${t.variables.map((v, i) => `\`{{${i + 1}}}\` = ${v}`).join(', ')}`,
      `- **Sample values (for Meta review):** ${t.variables.map((v, i) => `\`{{${i + 1}}}\` = ${SAMPLES[v]}`).join(', ')}`,
      '',
    );
    for (const lang of TEMPLATE_LANGUAGES) {
      out.push(`**${LANGUAGE_NAMES[lang]}**`, '', '```text', t.body[lang], '```', '');
      const buttons: readonly { text: Record<string, string> }[] = t.buttons;
      if (buttons.length)
        out.push(`Quick-reply buttons: ${buttons.map((b) => `\`${b.text[lang]}\``).join(' · ')}`, '');
    }
  }
  return out.join('\n');
}

const SAMPLES: Record<string, string> = {
  first_name: 'Priya',
  business_name: 'Smile Dental',
  assistant_name: 'Asha',
  'appointment.service': 'consultation',
  'appointment.time': '6 Oct, 11:30 AM',
  'appointment.date': '6 Oct',
  review_link: 'https://g.page/r/example/review',
};

if (import.meta.main) {
  writeFileSync(TEMPLATES_DOC_PATH, renderTemplatesDoc());
  console.log(`wrote ${TEMPLATES_DOC_PATH}`);
}
